/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package A1;
import java.util.ArrayList;
import java.util.Arrays ;

//import com.google.common.graph.ElementOrder.Type;

public class Program {
    public static int MaximumValue(int... inputs){
        int max=inputs[0];
        for (int i : inputs) {
            if(i>max)
              max=i;
        }
        return max;
    }
    public static Integer[] sort_array(Integer[] arr){
        int n = arr.length; 
        for (int i = 0; i < n-1; i++) 
        { int min_idx = i; 
            for (int j = i+1; j < n; j++) 
                if (arr[j] < arr[min_idx]) 
                    min_idx = j; 
            int temp = arr[min_idx]; 
            arr[min_idx] = arr[i]; 
            arr[i] = temp; }
        return arr;
    }


    public static String[] stringsort(String[] c){
        int size =c.length;
      for(int a = 0; a < size - 1; a++) 
      {
         for(int b = a + 1; b < c.length; b++) 
         {
            if(c[a].compareTo(c[b]) > 0) 
            {
               String temp = c[a];
               c[a] = c[b];
               c[b] = temp;
            }
         }
      }

        return c;
    }


    public static Integer[] CommonIntegerElements(Integer[] a ,Integer[] b) {
        Integer[]c=new Integer[0];
        int n=0;
       for (Integer i : a) {
           for (Integer j : b) {
               if(i==j){
                n=c.length;
                c= Arrays.copyOf(c,n+1);
                c[n]=i;
               }   
           }
       }
       c=sort_array(c);
    
        return c;
    }
    public static String[] CommonStringElements(String[] st1,String[] st2){
        String[] common=new String[0];
        int n=0;
        for (String st : st1) {
            for (String str : st2) {
                if(st==str){
                    n=common.length;
                    common=Arrays.copyOf(common,n+1);
                        common[n]=st;
                }
            }  
        }
        common=stringsort(common);
       // Arrays.sort(common);
        return common;
    }

    public static  <_Type> ArrayList <_Type>CommonElements(_Type[] a,_Type[] b){
      ArrayList <_Type> common=new ArrayList<_Type>();
      for (_Type t1: a) {
          for (_Type t2 : b) {
              if(t1==t2){
                  common.add(t1);
              } 
          }
      }
        return common;
    }



    public static void main(String[] args) {
       
        }
        
    }


